---
- name: install glance
  apt: name=glance state=present

- name: stop glance
  service: name=glance-{{ item }} state=stopped
  when: glance_force_init == True
  with_items:
  - registry
  - api

- name: drop glance DB
  mysql_db: name={{ mysql_glance_db }} state=absent login_host={{ mysql_login_host }} login_user={{ mysql_login_user }} login_password={{ mysql_login_password }}
  when: glance_force_init == True

- name: create glance DB
  mysql_db: name={{ mysql_glance_db }} state=present login_host={{ mysql_login_host }} login_user={{ mysql_login_user }} login_password={{ mysql_login_password }}

- name: create glance user
  mysql_user: name={{ mysql_glance_user }} state=present host='{{ item }}' password="{{ mysql_glance_password }}" priv={{ mysql_glance_db }}.*:ALL login_user={{ mysql_login_user }} login_password={{ mysql_login_password }} login_host={{ mysql_login_host }}
  with_items: groups['glance']

# configure glance-api.conf
# configure glance-regsitry.conf
- name: configure glance services
  template: src=glance-{{ item }}.conf.j2 dest=/etc/glance/glance-{{ item }}.conf backup=yes
  with_items:
  - registry
  - api

#By default, the Ubuntu packages create an SQLite database. Delete the glance.sqlite file created in the /var/lib/glance/
- name: Remove default glance.sqlite DB
  file:  path=/var/lib/glance/glance.sqlite state=absent

# # Initialize the database schema. A deprecation warning is OK...
# sudo -u glance glance-manage db_sync

- name: Glance db sync
  glance_manage: action=db_sync

- name: Register glance on keystone
  keystone_service: token={{ admin_token }} name=glance type=image description="OpenStack Image Service" public_url="http://{{ glance_service_public_ip }}:9292"

# start glance
- name: restart glance
  service: name=glance-{{ item }} state=restarted enabled=yes
  with_items:
  - registry
  - api
