---
# Loosely based on:
# http://docs.openstack.org/icehouse/install-guide/install/apt/content/neutron-ml2-controller-node.html
# Controller node Neutron config
#
- name: Install required networking components
  apt: name={{ item }} state=present
  with_items:
    - neutron-server
    - neutron-plugin-ml2

- name: Configure Neutron
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { 'src': 'neutron.conf.j2', 'dest': '/etc/neutron/neutron.conf' }
    - { 'src': 'ml2_conf.ini.j2', 'dest': '/etc/neutron/plugins/ml2/ml2_conf.ini' }

- name: Restarting Services
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - neutron-server