---

- name: install rabbitmq-server
  apt: name=rabbitmq-server state=present

- name: rabbitmq-server | add rabbitmq-server iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 5672 -j ACCEPT -m comment --comment "rabbitmq-server"
  sudo: true
  when: iptablesrules.stdout.find("rabbitmq-server") == -1
 
- name: save iptables
  command: iptables-save
  sudo: true
 
- name: restart iptables
  service: name= ufw state=restarted
  sudo: true

- name: enable rabbitmq-server server
  service: name=rabbitmq-server state=started enabled=yes
