---

### actually needed on nodes and there it's covered by openstack-* 
### dependencies
## - name: install python-MySQL
##   yum: name=MySQL-python state=present
 
- name: install mysql server
  apt: name=mysql-server state=present

- name: configure MySQLd
  copy: src=my.cnf dest=/etc/mysql/my.cnf
  notify: restart mysqld

- name: Enable and startup service
  service: name=mysqld enabled=yes

#### Maybe better to do it from each node?
### - name: Add nodes to MySQL allowed list
###   shell: echo "{{ item }}" >> /tmp/log
###   with_items: ( groups['keystone']+groups['qpid'] ) | unique

- name: MySQL | add MySQL iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 3306 -j ACCEPT -m comment --comment "MySQL"
  sudo: true
  when: iptablesrules.stdout.find("MySQL") == -1
 
- name: save iptables
  command: iptables-save
  sudo: true
 
- name: restart iptables
  service: name= ufw state=restarted
  sudo: true
