---

- name: install keystone
  apt: name=keystone state=present

- name: stop keystone
  service: name=keystone state=stopped
  when: keystone_force_init == True

- name: drop keystone DB
  mysql_db: name={{ mysql_keystone_db }} state=absent login_host={{ mysql_login_host }} login_user={{ mysql_login_user }} login_password={{ mysql_login_password }}
  when: keystone_force_init == True

- name: create keystone DB
  mysql_db: name={{ mysql_keystone_db }} state=present login_host={{ mysql_login_host }} login_user={{ mysql_login_user }} login_password={{ mysql_login_password }}
  # with_items: groups['mysql']

- name: create keystone user
  mysql_user: name={{ mysql_keystone_user }} state=present host='{{ item }}' password="{{ mysql_keystone_password }}" priv={{ mysql_keystone_db }}.*:ALL login_user={{ mysql_login_user }} login_password={{ mysql_login_password}} login_host={{ mysql_login_host }}
  with_items: groups['keystone']

#[database]
#connection=mysql://keystone:keystone@localhost/keystone

### - name: configure keystone
###   shell: crudini --set /etc/keystone/keystone.conf database connection mysql://{{ mysql_keystone_user }}:{{ mysql_keystone_password }}@{{ item }}/{{ mysql_keystone_db }}
###   with_items: groups['mysql']
###   notify: restart keystone
#

- name: configure keystone
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf backup=yes
  notify: restart keystone

- name: enable keystone
  service: name=keystone enabled=yes
  notify: restart keystone

- name: start keystone
  service: name=keystone state=started
  when: keystone_force_init == True

##OStack  environment:
##OStack    SERVICE_TOKEN: "{{ admin_token }}"
##OStack    SERVICE_ENDPOINT: http://{{ ansible_default_ipv4['address'] }}:35357/v2.0

# - name: transfer keystone DB template
#   template: src=openstack-keystone-setup-data.xml.j2 dest=/etc/openstack-keystone-setup-data.xml backup=yes

- name: setup keystone access
  template: src=openstack-admin.rc.j2 dest=/etc/openstack-admin.rc mode=0640 owner=root group=root backup=yes

- name: Keystone db_sync
  keystone_manage: action=dbsync
  
- name: Restart Keystone
  service: name=keystone state=restarted

## ADMIN USER
- name: Create keystone admin tenant
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" tenant={{ keystone_admin_tenant }} tenant_description="Admin Tenant"

- name: Create keystone admin user
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" user={{ keystone_admin_username }} password={{ keystone_admin_password }} tenant={{ keystone_admin_tenant }} email={{ keystone_admin_email }}

- name: Create keystone admin role and link admin user
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" role=admin user={{ keystone_admin_username }} tenant={{ keystone_admin_tenant }}

- name: Add role _member_ to admin
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" role=_member_ tenant={{ keystone_admin_tenant }} user={{ keystone_admin_username }}

## DEMO USER
- name: Create keystone demo tenant
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" tenant={{ keystone_demo_tenant }} tenant_description="Admin Tenant"

- name: Create keystone demo user
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" user={{ keystone_demo_username }} password={{ keystone_demo_password }} tenant={{ keystone_demo_tenant }} email={{ keystone_demo_email }}

- name: Create keystone demo role and link demo user
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" role=admin user={{ keystone_demo_username }} tenant={{ keystone_demo_tenant }}

- name: Add role _member_ to demo
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" role=_member_ tenant={{ keystone_demo_tenant }} user={{ keystone_demo_username }}


## SERVICE ENDPOINT
- name: Add keystone identity endpoint and service
  keystone_service: token={{ admin_token }} name=keystone type=identity description="Identity Service" public_url="http://{{ keystone_service_public_ip }}:5000/v2.0" region=regionOne
