---

- name: install nova and dependencies
  apt: name={{ item }} state=present
  with_items:
  - nova-api
  - nova-cert
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
  - python-novaclient

# https://answers.launchpad.net/nova/+question/225958
- name: start and enable dbus
  service: name=dbus state=started enabled=yes

- name: stop nova services
  service: name={{ item }} state=stopped
  when: nova_force_init == True
  with_items:
  - nova-api
  - nova-cert
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler

- name: configure nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf backup=yes

- name: Remove default db nova.sqlite database
  file: path=/var/lib/nova/nova.sqlite state=absent

- name: Create Nova user
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" user={{ nova_service_user }} password={{ nova_service_password }} email={{ nova_service_email }}

- name: Link nova user to admin role
  keystone_user: token={{ admin_token }} endpoint="http://{{ keystone_service_public_ip }}:35357/v2.0/" role=admin user={{ nova_service_user }} tenant={{ service_tenant }}


- name: Create keystone service
  keystone_service: token={{ admin_token }} name=nova type=compute description="Compute Service" public_url="http://{{ nova_service_public_ip }}:8774/v2/%\(tenant_id\)s"

- name: start and enable nova services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
  - nova-api
  - nova-scheduler
  - nova-conductor
  - nova-cert
  - nova-consoleauth
  - nova-novncproxy
