---

- name: install nova and dependencies
  yum: name={{ item }} state=present
  with_items:
  - nova-common
  - nova-api
  - nova-cert
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
  - python-novaclient

# https://answers.launchpad.net/nova/+question/225958
- name: start and enable messagebus
  service: name=messagebus state=started enabled=yes

- name: stop nova services
  service: name={{ item }} state=stopped
  when: nova_force_init == True
  with_items:
  - nova-api
  - nova-scheduler
  - nova-conductor
  - nova-cert

- name: drop nova DB
  mysql_db: name={{ mysql_nova_db }} state=absent login_host={{ mysql_login_host }} login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}
  when: nova_force_init == True

- name: create nova DB
  mysql_db: name={{ mysql_nova_db }} state=present login_host={{ mysql_login_host }} login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}

- name: create nova user
  mysql_user: name={{ mysql_nova_user }} state=present host='{{ item }}' password="{{ mysql_nova_password }}" priv={{ mysql_nova_db }}.*:ALL  login_host={{ mysql_login_host }} login_user={{ mysql_login_user }} login_password={{ mysql_login_password }}
  with_items: groups['nova']

- name: configure nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf backup=yes

- name: Remove default db nova.sqlite database
  file: path=/var/lib/nova/nova.sqlite state=absent

- name: initialize DB
  shell: nova-manage db sync
  when: nova_force_init == True

- name: start and enable nova services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - nova-api
  - nova-scheduler
  - nova-conductor
  - nova-cert
  - nova-consoleauth
  - nova-novncproxy
