---

- name: install nova and dependencies
  apt: name={{ item }} state=present
  with_items:
  - nova-compute-kvm
  - python-guestfs
  - python-mysqldb

- name: Make kernel readable from non root users
  shell: dpkg-statoverride --force --update --add root root 0644 /boot/vmlinuz-$(uname -r)

- name: Make kernel readable from non root persistent
  copy: src=templates/statoverride dest=/etc/kernel/postinst.d/statoverride owner=root mode=0755

- name: stop nova services
  service: name={{ item }} state=stopped
  when: nova_force_init == True
  with_items:
  - nova-compute

- name: configure nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf backup=yes

- name: Remove default nova.sqlite DB
  file: path=/var/lib/nova/nova.sqlite state=absent

- name: start and enable nova services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
  - nova-compute
